{
 "title": "All",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cpu",
    "label": "CPU",
    "query": "label_values(node_cpu_seconds_total, cpu)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "content": "\n## About\n\nHere you can find panels with common metrics that might help you troubleshoot why you're having problems with your system.\n\nTo exercise these metrics you can use [`chicken-gun`](https://github.com/cirocosta/chicken-gun), a tool aimed at stressing particular subsystems of your \nhosts so that you can ensure that you're measuring the right things, and your system is resilient.\n\nEach metric graphed in the format of panels contain a description on its right with pointers to `chicken-gun`'s documentation on how that particular measurement\ncan be exercised.\n\n"
  },
  {
   "title": "Logical CPUs",
   "type": "singlestat",
   "description": "Information about each CPU online can be found at  `/proc/cpuinfo`.\n\n`sysfs` can also be a source of information, including topology and connectivity: see `/sys/devices/system/cpu/cpuX/...`.",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"idle\"}) without (cpu,mode)"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "description": "See `/proc/meminfo`.\n\n- `MemTotal`: Total usable ram (i.e. physical ram minus a few reserved bits and the kernel binary code).",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 2 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "See `/proc/stat`:\n\n- `btime`: time at which the system booted, in seconds since the Unix epoch.",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 5 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "type": "graph",
     "gridPos": { "h": 11, "w": 15, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "irate(node_cpu_seconds_total{cpu=~\"$cpu\", mode!=\"idle\"}[3m])",
       "legendFormat": "{{ mode }} - {{ cpu }}"
      },
      {
       "expr": "1 - irate(node_cpu_seconds_total{cpu=~\"$cpu\", mode=\"idle\"}[3m])",
       "legendFormat": "non-idle - {{ cpu }}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 11, "w": 9, "x": 15, "y": 8 },
     "content": "| metric | description |\n| ------ | ----------- |\n| user   | normal processes executing in user mode |\n| nice   | `nice`d processes executing in user mode |\n| system | processes executing in kernel mode |\n| idle | idle |\n| iowait | time during which a particular CPU was idle and there was at least one outstanding disk I/O operation requested by a task scheduled on that CPU (at the time it generated that I/O request) |\n| non-idle | `1 - idle`, including the overheads not present in other metrics (e.g., context switching) |\n\n"
    }
   ]
  },
  {
   "title": "Disk throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "type": "graph",
     "gridPos": { "h": 11, "w": 15, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "bps", "label": "data rate" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total[3m]) * 8",
       "legendFormat": "rx {{ device }}"
      },
      {
       "expr": "irate(node_disk_written_bytes_total[3m]) * 8",
       "legendFormat": "tx {{ device }}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 11, "w": 9, "x": 15, "y": 9 },
     "content": "| metric | description |\n| ------ | ----------- |\n| `todo` | todo |\n"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "type": "graph",
     "gridPos": { "h": 11, "w": 15, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "processes in state" }
     ],
     "targets": [
      { "expr": "node_procs_running", "legendFormat": "running" },
      { "expr": "node_procs_blocked", "legendFormat": "blocked" },
      { "expr": "irate(node_forks_total[3m])", "legendFormat": "fork rate" }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 11, "w": 9, "x": 15, "y": 10 },
     "content": "| metric | description |\n| ------ | ----------- |\n| `running` | total number of threads that are running or ready to run (i.e., the total number of runnable threads) |\n| `blocked` | number of threads currently blocked, waiting for I/O to complete |\n| `forks /s` | rate of the number of processes and threads created, which includes (but  is not limited  to) those  created by  calls to the  [`fork()`][fork] and [`clone()`][clone] system calls |\n\n\n[fork]: http://man7.org/linux/man-pages/man2/fork.2.html\n[clone]: http://man7.org/linux/man-pages/man2/clone.2.html"
    }
   ]
  }
 ]
}