apiVersion: apps/v1
{{- if .Values.persistence.enabled }}
kind: StatefulSet
{{- else }}
kind: Deployment
{{- end }}
metadata:
  name: {{ include "cg.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cg.name" . }}
    helm.sh/chart: {{ include "cg.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cg.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cg.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 3
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: 
            - cg
          args:
          {{- if not (empty .Values.args) }}
            {{- toYaml .Values.args | nindent 12 }}
          {{- else }}
            {{- fail "args for the cg command must be specified" }}
          {{- end }}
          ports:
            - name: tcp
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- if .Values.additionalVolumeMounts }}
{{ toYaml .Values.additionalVolumeMounts | indent 12 }}
          {{- end }}
          {{- if .Values.persistence.enabled }}
            - name: persistent-disk
              mountPath: /mnt/pd
          {{- end }}
      {{- if .Values.additionalVolumes }}
      volumes:
{{ toYaml .Values.additionalVolumes | indent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: persistent-disk
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
      {{- if .Values.persistence.storageClassName }}
      {{- if (eq "-" .Values.persistence.storageClassName) }}
        storageClassName: ""
      {{- else }}
        storageClassName: "{{ .Values.persistence.storageClassName }}"
      {{- end }}
      {{- end }}
  {{- end }}
