---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/builder}

params:
  REPOSITORY: cirocosta/pageok
  TAG: latest
  CONTEXT: repository

inputs:
- name: repository

outputs:
- name: image

caches:
- path: cache

run: {path: build}
