version: '3.7'

services:
  prometheus:
    container_name: prometheus
    ports: [ '9090:9090' ]
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    container_name: grafana
    ports: [ '3000:3000' ]
    image: grafana/grafana
    volumes:
      - ./grafana/config.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
